# Generated by Django 4.2.1 on 2023-05-28 18:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("demo3", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "company",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=2, null=True),
                ),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=14, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
