# Generated by Django 4.2.3 on 2023-07-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo3", "0004_personproxy_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=2000)),
                ("name", models.CharField(max_length=2000)),
                ("source", models.CharField(max_length=2000)),
            ],
        ),
    ]
